package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	mgo "gopkg.in/mgo.v2"
	"gopkg.in/mgo.v2/bson"
)

var startTime = time.Now()
var db *mgo.Database

const (
	COLLECTION = "tracks"
)

var IGF = IgcFiles{
	Address:  os.Getenv("MONGO_ADDRESS"),
	Database: os.Getenv("MONGO_DATABASE"),
	Username: os.Getenv("MONGO_USER"),
	Password: os.Getenv("MONGO_PASSWORD"),
}

func main() {
	fmt.Println("Starting main")

	// Connects to the databse
	IGF.Connect()

	// Sends every request to the router function with Regex.
	http.HandleFunc("/", handleRouter)

	//Listens to the Url given by heroku
	if err := http.ListenAndServe(":"+os.Getenv("MONGO_PORT"), nil); err != nil {
		// If the Url is wrong the program shuts down immediately.
		log.Fatal(err)
	}

}

func (m *IgcFiles) Connect() {
	fmt.Println("Connecting to database")
	session := &mgo.DialInfo{
		Addrs:    []string{m.Address},
		Timeout:  60 * time.Second,
		Database: m.Database,
		Username: m.Username,
		Password: m.Password,
	}

	connection, err := mgo.DialWithInfo(session)
	if err != nil {
		log.Fatal(err)
	}
	db = connection.DB(m.Database)
}

// This function is for inserting a document into the databse
func (m *IgcFiles) Insert(track Track) error {
	fmt.Println("Trying to insert into the db")
	// Inserts the track parameter into the right collection in the database.
	// returns error if failed
	err := db.C(COLLECTION).Insert(&track)
	return err
}

// This function returns all documents from a collection in the database
func (m *IgcFiles) FindAll() ([]Track, error) {
	fmt.Println("Trying to find all")
	var tracks []Track
	// Using the nil parameter in find gets all tracks
	err := db.C(COLLECTION).Find(nil).All(&tracks)
	return tracks, err
}

// This function finds one document in the collection based in the id parameter
func (m *IgcFiles) FindOne(id string) (Track, error) {
	fmt.Println("Trying to find one by id")
	var track Track
	// Using bson.ObjectIdHex to convert the ID send to a hex,
	// then compares it to the hexadesimal IDs generated by mongodb
	err := db.C(COLLECTION).FindId(bson.ObjectIdHex(id)).One(&track)
	return track, err
}

// This function returns the latest inserted document in the database
func (m *IgcFiles) FindLatest() (Track, error) {
	var track Track
	// Returns the first object of all documents sorted by "_id"
	err := db.C(COLLECTION).Find(nil).Sort("-_id").One(&track)
	return track, err
}

// This function returns an int with the count of how many documents
// are in a collection in the database
func (m *IgcFiles) FindCount() (int, error) {
	trackCount, err := db.C(COLLECTION).Count()
	return trackCount, err
}

// This function deletes all documents in a collection
func (m *IgcFiles) DeleteAll() (*mgo.ChangeInfo, error) {
	rem, err := db.C(COLLECTION).RemoveAll(nil)
	return rem, err
}

func (m *IgcFiles) FindOldest() ([]Track, error) {
	var tracks []Track
	// Gets the first object when documents are sorted reverse order by giving "-" to _id
	err := db.C(COLLECTION).Find(nil).Sort("_id").All(&tracks)
	return tracks, err
}

func (m *IgcFiles) FindOldest(id int) ([]Track, error) {
	var tracks []Track
	// Gets the first object when documents are sorted reverse order by giving "-" to _id
	err := db.C(COLLECTION).Find(nil).Sort("_id").All(&tracks)
	return tracks, err
}
